services:
  - type: web
    name: ai-praktikrapport-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: SECRETAPIKEY
        sync: false
